# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'askPause.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AskPauseWindow(object):
    def setupUi(self, AskPauseWindow):
        AskPauseWindow.setObjectName("AskPauseWindow")
        AskPauseWindow.resize(626, 515)
        self.verticalLayout = QtWidgets.QVBoxLayout(AskPauseWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_browser = QtWidgets.QTextBrowser(AskPauseWindow)
        self.message_browser.setObjectName("message_browser")
        self.verticalLayout.addWidget(self.message_browser)
        self.notes_field = QtWidgets.QTextEdit(AskPauseWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_field.sizePolicy().hasHeightForWidth())
        self.notes_field.setSizePolicy(sizePolicy)
        self.notes_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.notes_field.setFont(font)
        self.notes_field.setObjectName("notes_field")
        self.verticalLayout.addWidget(self.notes_field)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.terminate_button = QtWidgets.QPushButton(AskPauseWindow)
        self.terminate_button.setObjectName("terminate_button")
        self.buttons_layout.addWidget(self.terminate_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem)
        self.resume_button = QtWidgets.QPushButton(AskPauseWindow)
        self.resume_button.setObjectName("resume_button")
        self.buttons_layout.addWidget(self.resume_button)
        self.verticalLayout.addLayout(self.buttons_layout)

        self.retranslateUi(AskPauseWindow)
        QtCore.QMetaObject.connectSlotsByName(AskPauseWindow)

    def retranslateUi(self, AskPauseWindow):
        _translate = QtCore.QCoreApplication.translate
        AskPauseWindow.setWindowTitle(_translate("AskPauseWindow", "Dialog"))
        self.message_browser.setHtml(_translate("AskPauseWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.terminate_button.setText(_translate("AskPauseWindow", "Terminate"))
        self.resume_button.setText(_translate("AskPauseWindow", "Resume"))
