# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatLogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatLogWindow(object):
    def setupUi(self, ChatLogWindow):
        ChatLogWindow.setObjectName("ChatLogWindow")
        ChatLogWindow.resize(637, 578)
        self.centralwidget = QtWidgets.QWidget(ChatLogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatLog = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.chatLog.setFont(font)
        self.chatLog.setObjectName("chatLog")
        self.verticalLayout.addWidget(self.chatLog)
        ChatLogWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChatLogWindow)
        self.statusbar.setObjectName("statusbar")
        ChatLogWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChatLogWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatLogWindow)

    def retranslateUi(self, ChatLogWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatLogWindow.setWindowTitle(_translate("ChatLogWindow", "MainWindow"))
