# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget


class Ui_MainWindow(object):
    macrosTable: QTableWidget

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadButton.setFlat(False)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout.addWidget(self.reloadButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pollRateLabel = QtWidgets.QLabel(self.centralwidget)
        self.pollRateLabel.setObjectName("pollRateLabel")
        self.horizontalLayout.addWidget(self.pollRateLabel)
        self.pollRate = QtWidgets.QSpinBox(self.centralwidget)
        self.pollRate.setMinimum(500)
        self.pollRate.setMaximum(999999999)
        self.pollRate.setSingleStep(50)
        self.pollRate.setObjectName("pollRate")
        self.horizontalLayout.addWidget(self.pollRate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.soundCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.soundCheckbox.setObjectName("soundCheckbox")
        self.horizontalLayout.addWidget(self.soundCheckbox)
        self.lolCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.lolCheckbox.setObjectName("lolCheckbox")
        self.horizontalLayout.addWidget(self.lolCheckbox)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.macrosTable = QtWidgets.QTableWidget(self.centralwidget)
        self.macrosTable.setObjectName("macrosTable")
        self.macrosTable.setColumnCount(0)
        self.macrosTable.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.macrosTable)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pollCountdown = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pollCountdown.sizePolicy().hasHeightForWidth())
        self.pollCountdown.setSizePolicy(sizePolicy)
        self.pollCountdown.setMinimumSize(QtCore.QSize(0, 0))
        self.pollCountdown.setProperty("value", 24)
        self.pollCountdown.setObjectName("pollCountdown")
        self.horizontalLayout_3.addWidget(self.pollCountdown)
        self.toggleButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleButton.setObjectName("toggleButton")
        self.horizontalLayout_3.addWidget(self.toggleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Hyakuretsu"))
        self.reloadButton.setText(_translate("MainWindow", "Reload"))
        self.pollRateLabel.setText(_translate("MainWindow", "Poll rate (ms)"))
        self.soundCheckbox.setText(_translate("MainWindow", "Sound"))
        self.lolCheckbox.setText(_translate("MainWindow", "Hokkto"))
        self.toggleButton.setText(_translate("MainWindow", "Start"))
